In [18]:
import torch
import numpy as np

print(torch.__version__)

1.0.0


torch模块包含了Tensor以及大量对Tensor的操作(e.g. 检索、序列化、reshape等)

### 创建Tensor

In [25]:
# torch.tensor(data, )
torch.tensor([[1.,2,3], [2,5,8]])

tensor([[1., 2., 3.],
        [2., 5., 8.]])

In [26]:
# create Tensor from numpy.ndarray
a = np.array([1,2,3.], dtype=np.float32) # Do not forget to set dtype to np.float32
torch.from_numpy(a)

tensor([1., 2., 3.])

In [29]:
# torch.tensor()可以接受scalar，此时创建的tensor.dim()=0
a = torch.tensor(1)
print(a.dim())
a.size()

0


torch.Size([])

#### 创建指定size()的Tensor

各种创建方法的区别是如何初始化这个Tensor

In [30]:
# 不初始化
torch.empty(3, 5)

tensor([[ 0.0000e+00, -4.6566e-10, -3.5064e+05,  3.6902e+19,  2.3058e+20],
        [ 6.2689e+22,  4.7428e+30,  0.0000e+00,  0.0000e+00, -4.6566e-10],
        [ 0.0000e+00, -4.6566e-10,  6.2957e+34,  6.8927e+34,  8.5771e-39]])

In [31]:
# 初始化为0
torch.zeros(3, 5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [32]:
# 初始化为1
torch.ones(3, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [33]:
# 初始化为某个指定值
torch.full((3, 2), 1.5)

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000],
        [1.5000, 1.5000]])

###  创建和某个Tensor的size相同的Tensor

各种方法的区别是如何初始化元素值

In [34]:
torch.zeros_like(torch.ones(3,6))

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [35]:
torch.ones_like(torch.zeros(3,6))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [36]:
torch.full_like(torch.ones(3,5), 2.2)

tensor([[2.2000, 2.2000, 2.2000, 2.2000, 2.2000],
        [2.2000, 2.2000, 2.2000, 2.2000, 2.2000],
        [2.2000, 2.2000, 2.2000, 2.2000, 2.2000]])

### 创建一些特殊的一维或二维Tensor

In [37]:
torch.arange(5)
torch.arange(1, 5)
torch.arange(1, 5, 0.5)

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000])

In [38]:
torch.linspace(-5, 2, steps=20)

tensor([-5.0000, -4.6316, -4.2632, -3.8947, -3.5263, -3.1579, -2.7895, -2.4211,
        -2.0526, -1.6842, -1.3158, -0.9474, -0.5789, -0.2105,  0.1579,  0.5263,
         0.8947,  1.2632,  1.6316,  2.0000])

In [39]:
# 创建单位矩阵
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## 数据聚合、切分操作

* cat 👍👍👍👍👍
* stack   👍👍👍
* chunk   👍👍👍
* split   👍👍👍👍

**cat** 拼接. 将一组tensor拼接成一个tensor，除了指定维度，其他维度的size必须相同

In [47]:
x = torch.randn(2, 3)
print(torch.cat((x,x,x), 0))
torch.cat((x,x,x), 1)

tensor([[ 1.8999, -0.4945,  0.8681],
        [ 0.0946, -0.0116, -1.3992],
        [ 1.8999, -0.4945,  0.8681],
        [ 0.0946, -0.0116, -1.3992],
        [ 1.8999, -0.4945,  0.8681],
        [ 0.0946, -0.0116, -1.3992]])


tensor([[ 1.8999, -0.4945,  0.8681,  1.8999, -0.4945,  0.8681,  1.8999, -0.4945,
          0.8681],
        [ 0.0946, -0.0116, -1.3992,  0.0946, -0.0116, -1.3992,  0.0946, -0.0116,
         -1.3992]])

In [48]:
x1 = torch.randn(2, 3)
x2 = torch.randn(3, 3)
print(x1)
print(x2)
torch.cat((x1, x2), 0)

tensor([[ 0.8112, -0.1622, -0.3556],
        [ 0.1400,  1.0407, -1.5378]])
tensor([[-1.4780, -1.2352,  0.8683],
        [-1.0848,  1.8059, -0.3266],
        [-0.5018,  0.4598, -1.5580]])


tensor([[ 0.8112, -0.1622, -0.3556],
        [ 0.1400,  1.0407, -1.5378],
        [-1.4780, -1.2352,  0.8683],
        [-1.0848,  1.8059, -0.3266],
        [-0.5018,  0.4598, -1.5580]])

**stack**: 对一组tensor进行concat，但要求每个tensor的size必须相同, torch.cat is better

In [49]:
x = torch.randn(2, 3)
y = torch.randn(2, 3)
torch.stack((x, y), 0)

tensor([[[-0.8104, -0.1352, -0.9820],
         [-0.6749, -0.7109, -0.6862]],

        [[ 0.3144,  0.0240, -0.9036],
         [-1.5012,  0.0268, -0.2666]]])

**chunk**: 将一个tensor切分为多个tensor，需要指定tensor个数，返回tuple类型

In [51]:
x = torch.randn(2, 5)
x

tensor([[-0.0717,  0.4842,  2.0958,  0.0026, -0.9535],
        [-0.1018,  0.4900, -0.2004,  0.7950,  1.5493]])

In [52]:
print(torch.chunk(x, 2, 0)[0])
print(torch.chunk(x, 2, 0)[1])


tensor([[-0.0717,  0.4842,  2.0958,  0.0026, -0.9535]])
tensor([[-0.1018,  0.4900, -0.2004,  0.7950,  1.5493]])


In [53]:
print(torch.chunk(x, 5, 1)[0])
print(torch.chunk(x, 5, 1)[1])

tensor([[-0.0717],
        [-0.1018]])
tensor([[0.4842],
        [0.4900]])


**split**: 将一个tensor切分为多个tensor

torch.split(tensor, split_size_or_sections, dim=0)

**split_size_or_sections 指定每块的大小, 而torch.chunk()是指定切分多少块**

如果split_size_or_sections是整数，此时split()功能退化为chunk()

如果split_size_or_sections是list,则把tensor切分成len(split_size_or_sections)个tensor，

每一个的tensor在dim的size是 split_size_or_sections的值


In [54]:
x = torch.randn(3, 3)
x

tensor([[-1.7579,  1.7611, -1.7600],
        [ 1.7105,  0.7433, -0.2414],
        [-1.3782, -2.0336,  0.2646]])

In [55]:
torch.chunk(x, 3, 0) # 切分为3个

(tensor([[-1.7579,  1.7611, -1.7600]]),
 tensor([[ 1.7105,  0.7433, -0.2414]]),
 tensor([[-1.3782, -2.0336,  0.2646]]))

In [56]:
torch.split(x, 1, 0) # 每个在dim_0的size=1，意思也是切分为3个

(tensor([[-1.7579,  1.7611, -1.7600]]),
 tensor([[ 1.7105,  0.7433, -0.2414]]),
 tensor([[-1.3782, -2.0336,  0.2646]]))

In [57]:
torch.split(x, [1, 2], 0)

(tensor([[-1.7579,  1.7611, -1.7600]]), tensor([[ 1.7105,  0.7433, -0.2414],
         [-1.3782, -2.0336,  0.2646]]))

### 检索/切片 👍👍👍👍👍



* torch.gather
* torch.index_select
* torch.masked_select
* torch.narrow
* torch.nonzero


**gather**: 在指定维度，把index作为下标检索数据
```
torch.gather(input, dim, index)
```

以3-D tensor为例:

```
out[i][j][k] = input[index[i][j][k]][j][k]   # if dim=0

out[i][j][k] = input[i][index[i][j][k]][k]   # if dim=1

out[i][j][k] = input[i][j][index[i][j][k]]   # if dim=2
```

**tensor和index的维度相同**

如果tensor的size($x_{0}, x_{1},...,x_{i-1},x_{i},x_{i+1},...,x_{n-1}$)，dim=i，那么index的size必须是($x_{0}, x_{1},...,x_{i-1},y,x_{i+1},...,x_{n-1}$), y>=1

**返回的tensor和index的size完全相同**

In [58]:
x = torch.randn(2, 3, 5)
print(x)

index = torch.topk(x, 2, 2)[1]
index # (2, 3, 2)

tensor([[[ 0.2771, -0.3214,  0.1635,  0.2951, -0.6361],
         [-0.5465, -0.4658, -1.2455,  0.0858,  1.9950],
         [ 0.9819,  0.1533, -0.7084,  0.8812,  1.0277]],

        [[ 0.6067,  0.0650,  0.4928,  1.5286, -0.5206],
         [-2.2998, -0.4075,  1.1956, -0.7620, -0.3332],
         [ 0.4792,  1.0548, -0.0824, -0.5201, -1.6686]]])


tensor([[[3, 0],
         [4, 3],
         [4, 0]],

        [[3, 0],
         [2, 4],
         [1, 0]]])

In [59]:
torch.gather(x, 2, index)

tensor([[[ 0.2951,  0.2771],
         [ 1.9950,  0.0858],
         [ 1.0277,  0.9819]],

        [[ 1.5286,  0.6067],
         [ 1.1956, -0.3332],
         [ 1.0548,  0.4792]]])

In [60]:
data

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
index

tensor([[[3, 0],
         [4, 3],
         [4, 0]],

        [[3, 0],
         [2, 4],
         [1, 0]]])

In [62]:
x = torch.arange(24).view(2, 3, 4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [63]:
index = torch.ones(2,2,4, dtype=torch.long)
index

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [64]:
torch.gather(x, 1, index)

tensor([[[ 4,  5,  6,  7],
         [ 4,  5,  6,  7]],

        [[16, 17, 18, 19],
         [16, 17, 18, 19]]])